version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/guides/orchestrate/jobs-steps/#jobs-overview & https://circleci.com/docs/reference/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: cimg/node:22.19.0

    steps:
      - checkout # Checkout the code as the first step.
      - run:
          name: "Install dependencies"
          command: "npm ci"
      - run:
          name: "Build"
          command: "npx nx affected:run build"
      - run:
          name: "Test"
          command: "npx nx affected:run test"
      - run:
          name: "Lint"
          command: "npx nx affected:run lint"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/guides/orchestrate/workflows/ & https://circleci.com/docs/reference/configuration-reference/#workflows
workflows:
  say-hello-workflow: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build