name: Build, Test and Lint

on:
  pull_request:
    branches: [main, develop]

jobs:
  build-test-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.19.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build affected projects
        run: npx nx affected:build --output-style=static

      - name: Test affected projects
        run: npx nx affected:test --output-style=static

      - name: Lint affected projects
        run: npx nx affected:lint --output-style=static
